license="${mod_license}"

[[mods]]
modId="${neoforge_mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_sources_url}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="increased-chat-height.common.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${neoforge_mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${neoforge_mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_minor_version},26.2)"
ordering="NONE"
side="CLIENT"
